// <auto-generated />
using System;
using System.Collections.Generic;
using EFCore.MigrationExtensions.SqlObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Outbox;

#nullable disable

namespace Outbox.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519062044_AddPartitionNumber")]
    partial class AddPartitionNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.Model.AddSqlObjects(new SqlObject[]
            {
                new("insert_outbox_message.sql", "CREATE OR REPLACE PROCEDURE outbox.insert_outbox_message(IN ptopic character varying, IN ppartition integer, IN type character varying, IN key character varying, IN payload jsonb, IN headers jsonb)\n LANGUAGE plpgsql\nAS $procedure$\nDECLARE\ncounter int;\nBEGIN\nupdate outbox.outbox_offset_sequences\nset value = value + 1\nwhere topic = ptopic and partition = ppartition\nreturning value into counter;\ninsert into outbox.outbox_messages(topic, partition, type, key, payload, headers, number)\nvalues (ptopic, ppartition, type, key, payload, headers, counter);\nEND;\n$procedure$\n;\n")
                {
                    Order = 2147483647
                },
            });

            modelBuilder
                .HasDefaultSchema("outbox")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Outbox.Entities.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Dictionary<string, string>>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("Topic", "Partition", "Number")
                        .HasDatabaseName("ix_outbox_messages_topic_partition_number");

                    b.ToTable("outbox_messages", "outbox");
                });

            modelBuilder.Entity("Outbox.Entities.OutboxOffset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AvailableAfter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_after")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LastProcessedNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_processed_number");

                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_offsets");

                    b.HasIndex("Topic", "Partition")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_offsets_topic_partition");

                    b.ToTable("outbox_offsets", "outbox");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AvailableAfter = new DateTimeOffset(new DateTime(2025, 5, 18, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastProcessedNumber = 0,
                            Partition = 0,
                            Topic = "topic-1"
                        },
                        new
                        {
                            Id = 3,
                            AvailableAfter = new DateTimeOffset(new DateTime(2025, 5, 18, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            LastProcessedNumber = 0,
                            Partition = 1,
                            Topic = "topic-1"
                        });
                });

            modelBuilder.Entity("Outbox.Entities.OutboxOffsetSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Partition")
                        .HasColumnType("integer")
                        .HasColumnName("partition");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("topic");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_outbox_offset_sequences");

                    b.ToTable("outbox_offset_sequences", "outbox");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Partition = 0,
                            Topic = "topic-1",
                            Value = 0
                        },
                        new
                        {
                            Id = 2,
                            Partition = 1,
                            Topic = "topic-1",
                            Value = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
